name: dependency-review
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Dependency Review
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4.1.1
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v3.1.4
      with:
        comment-summary-in-pr: true
        vulnerability-check: true
        license-check: true
        fail-on-severity: moderate