name: gradle-check
run-name: Gradle Check
on:
  workflow_call:
    inputs:
      ref:
        required: true
        description: "The branch to checkout and work-on"
        type: string
      pull_request:
        required: false
        description: "The Pull Request No."
        type: string
      update_type:
        required: false
        description: "Update type associated with dependabot PR"
        type: string
      sha:
        required: false
        description: "SHA of the commit"
        type: string
      actor:
        required: false
        description: "The actor associated with the PR"
        type: string
        default: ${{ github.actor }}
      commit_context:
        required: false
        description: "The context to use for commit status"
        type: string
        default: "Gradle Check"
      commit_label_prefix:
        required: false
        description: "The prefix to use for commit label"
        type: string
        default: "build_"
      gradle_version:
        required: false
        description: "Gradle version to use"
        type: string
        default: "8.14"
jobs:
  gradle:
    runs-on: ubuntu-latest
    name: Gradle Check
    steps:
      - name: Build Pending
        uses: quotidian-ennui/actions-olio/commit-status-and-label@main
        if: |
          inputs.pull_request != '' &&
          inputs.sha != ''
        with:
          state: pending
          sha: ${{ inputs.sha }}
          context: ${{ inputs.commit_context }}
          label_prefix: ${{ inputs.commit_label_prefix }}
      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 21
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
        id: setup_gradle
        with:
          gradle-version: ${{ inputs.gradle_version }}
      - name: Execute Check
        id: gradle
        env:
          JDK_JAVA_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
        run: |
          cd "${{ github.workspace }}/test" && gradle check
      - name: Gradle Build Reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-reports
          path: |
            **/build/reports
      - name: Build Result
        if: |
          (success() || failure()) &&
          inputs.pull_request != '' &&
          inputs.sha != ''
        uses: quotidian-ennui/actions-olio/commit-status-and-label@main
        with:
          state: ${{ steps.gradle.outcome }}
          sha: ${{ inputs.sha }}
          context: ${{ inputs.commit_context }}
          label_prefix: ${{ inputs.commit_label_prefix }}
