name: gradle

on:
  push:
    branches-ignore:
      - 'dependabot/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  gradle:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/gradle-check.yml
    with:
      ref: ${{ github.head_ref }}
