name: owasp
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  schedule:
    - cron: "15 03 * * SUN"
env:
  GRADLE_VERSION: "8.10.2"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  owasp:
    name: OWASP Dependency Check Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: 21
          distribution: "temurin"
      - name: Setup Ubuntu
        id: ubuntu-bootstrap
        run: |
          echo "today=$(/bin/date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          gradle-home-cache-excludes: dependency-check-data
      - name: OWASP dependency-check-data cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-dependency-check-data-${{ steps.ubuntu-bootstrap.outputs.today }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-data-
      - name: Gradle DependencyCheckAnalyze
        id: owasp
        env:
          JAVA_TOOL_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          cd "${{ github.workspace }}/test" && gradle dependencyCheckAnalyze
      - name: Update PR
        id: comment
        uses: quotidian-ennui/actions-olio/pr-or-issue-comment@main
        if: |
          (success() || failure()) &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.number != ''
        with:
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            OWASP Dependency Check: ${{ steps.owasp.outcome }}

            [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          search_term: "dependabot-action-dependency-check-analyze"
          token: ${{ github.token }}
