name: owasp
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  schedule:
    - cron: "15 03 * * SUN"
env:
  GRADLE_VERSION: 8.7
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  owasp:
    name: OWASP Dependency Check Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: 21
          distribution: "temurin"
      - name: Setup Ubuntu
        id: ubuntu-bootstrap
        run: |
          echo "today=$(/bin/date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
        with:
          gradle-home-cache-cleanup: true
          gradle-version: ${{ env.GRADLE_VERSION }}
          gradle-home-cache-excludes: dependency-check-data
      - name: OWASP dependency-check-data cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-dependency-check-data-${{ steps.ubuntu-bootstrap.outputs.today }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-data-
      - name: Gradle DependencyCheckAnalyze
        id: owasp
        env:
          JAVA_TOOL_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          cd "${{ github.workspace }}/test" && gradle dependencyCheckAnalyze
      - name: Update PR
        id: comment
        uses: quotidian-ennui/actions-olio/pr-or-issue-comment@main
        if: |
          (success() || failure()) &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.number != ''
        with:
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            OWASP Dependency Check: ${{ steps.owasp.outcome }}

            [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          search_term: "dependabot-action-dependency-check-analyze"
          token: ${{ github.token }}
