name: owasp
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  schedule:
    - cron: "15 03 * * SUN"
env:
  GRADLE_VERSION: 8.5
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  owasp:
    name: OWASP Dependency Check Analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: 21
          distribution: "temurin"
      - name: Setup Ubuntu
        id: ubuntu-bootstrap
        run: |
          echo "today=$(/bin/date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-home-cache-cleanup: true
          gradle-version: ${{ env.GRADLE_VERSION }}
          gradle-home-cache-excludes: dependency-check-data
      - name: OWASP dependency-check-data cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.gradle/dependency-check-data
          key: ${{ runner.os }}-dependency-check-data-${{ steps.ubuntu-bootstrap.outputs.today }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-data-
      - name: Gradle DependencyCheckAnalyze
        id: owasp
        env:
          JAVA_TOOL_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          cd "${{ github.workspace }}/test" && gradle dependencyCheckAnalyze
      - name: Update PR
        id: comment
        uses: quotidian-ennui/actions-olio/pr-or-issue-comment@main
        if: |
          (success() || failure()) &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.number != ''
        with:
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            OWASP Dependency Check: ${{ steps.owasp.outcome }}

            [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          search_term: "dependabot-action-dependency-check-analyze"
          token: ${{ github.token }}
