name: owasp

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "serviceTestLog4j2.xml"
      - "verifyLog4j2.xml"
  schedule:
    - cron: '15 03 * * SUN'

env:
  GRADLE_VERSION: 8.4

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  owasp:
    name: OWASP Dependency Check Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Setup Ubuntu
      id: ubuntu-bootstrap
      run: |
        echo "today=$(/bin/date -u '+%Y%m%d')" >> "$GITHUB_OUTPUT"
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.10.0
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}
        gradle-home-cache-excludes: dependency-check-data
    - name: OWASP dependency-check-data cache
      uses: actions/cache@v3.3.2
      with:
        path: ~/.gradle/dependency-check-data
        key: ${{ runner.os }}-dependency-check-data-${{ steps.ubuntu-bootstrap.outputs.today }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-data-
    - name: Gradle DependencyCheckAnalyze
      uses: gradle/gradle-build-action@v2.10.0
      continue-on-error: true
      env:
        JAVA_TOOL_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}
        arguments: dependencyCheckAnalyze
        build-root-directory: test