name: dependabot-build
run-name: Build PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.client_payload.base.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  build:
    uses: ./.github/workflows/gradle-check.yml
    with:
      ref: ${{ github.event.client_payload.base.ref }}
      sha: ${{ github.event.client_payload.base.sha }}
      pull_request: ${{ github.event.client_payload.detail.pull_request }}
      update_type: ${{ github.event.client_payload.detail.dependabot_update_type }}
      actor: ${{ github.event.client_payload.base.actor }}
