name: dependabot-build
run-name: Assess PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.client_payload.base.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  build:
    uses: ./.github/workflows/gradle-check.yml
    with:
      ref: ${{ github.event.client_payload.base.ref }}
      sha: ${{ github.event.client_payload.base.sha }}
      pull_request: ${{ github.event.client_payload.detail.pull_request }}
      update_type: ${{ github.event.client_payload.detail.dependabot_update_type }}
      actor: ${{ github.event.client_payload.base.actor }}

  dependabot_merge_gradle:
    runs-on: ubuntu-latest
    name: Dependabot Merge (gradle changes)
    needs:
      - build
    if: |
      github.event.client_payload.detail.pull_request != ''
    steps:
      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
      - name: Dependabot Merge
        id: dependabot_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@main
        with:
          # contents:write token will do here.
          # token: ${{ steps.app-token.outputs.token }}
          change_filter: "**/build.gradle"
          automerge_level: "semver-patch"

  dependabot_merge_actions:
    runs-on: ubuntu-latest
    name: Dependabot Merge (action changes)
    needs:
      - build
    if: |
      github.event.client_payload.detail.pull_request != ''
    steps:
      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
      - name: "Create Token"
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
      - name: Dependabot Merge
        id: dependabot_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@main
        with:
          # special token because modifying workflows
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
          automerge_level: "semver-patch|semver-minor"
