name: pr-trigger
run-name: PR Build Trigger
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  depbot-repo-dispatch:
    permissions:
      contents: write
      pull-requests: read
      issues: read
    runs-on: ubuntu-latest
    name: Dependabot Workflow Trigger
    steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@v1
      id: findpr
      with:
        github-token: ${{ github.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: Grab Dependabot metadata
      if: ${{ github.actor == 'dependabot[bot]' }}
      id: depbot-metadata
      continue-on-error: true
      uses: dependabot/fetch-metadata@v1
    - name: dispatch
      id: dispatch
      uses: quotidian-ennui/actions-olio/repo-dispatch@main
      with:
        event_type: pr-build
        token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
        ref: ${{ github.head_ref }}
        event_detail: |
          {
            "pull_request": "${{ steps.findpr.outputs.pr }}",
            "dependabot_update_type": "${{ steps.depbot-metadata.outputs.update-type || 'unknown' }}"
          }
