name: updatecli
on:
  workflow_dispatch: null
  schedule:
    - cron: '15 03 * * SUN'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  UPDATECLI_VERSION: v0.70.0
  UPDATECLI_GITHUB_USER: qe-repo-updater[bot]
  UPDATECLI_GITHUB_EMAIL: 152897211+qe-repo-updater[bot]@users.noreply.github.com
jobs:
  updatecli:
    name: Run updatecli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Setup updatecli"
        uses: updatecli/updatecli-action@7443aa3f35bcc6a9061030d73e953bf6ede758f9 # v2.52.0
        with:
          version: ${{ env.UPDATECLI_VERSION }}
      - uses: actions/create-github-app-token@f04aa94d10cf56334d1c580e077ce2e3569e805d # v1.6.3
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: "UpdateCLI"
        run: |
          updatecli apply
        env:
          UPDATECLI_GITHUB_USER: ${{ env.UPDATECLI_GITHUB_USER }}
          UPDATECLI_GITHUB_EMAIL: ${{ env.UPDATECLI_GITHUB_EMAIL }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          UPDATECLI_GH_ACTION: true
