name: updatecli
on:
  workflow_dispatch: null
  schedule:
    - cron: '15 03 * * SUN'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  UPDATECLI_VERSION: v0.72.0
  UPDATECLI_GITHUB_USER: qe-repo-updater[bot]
  UPDATECLI_GITHUB_EMAIL: 152897211+qe-repo-updater[bot]@users.noreply.github.com
jobs:
  updatecli:
    name: Run updatecli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Setup updatecli"
        uses: updatecli/updatecli-action@ecfc21fd2d9e91be2af8b706ea10aea5154f6d5d # v2.54.0
        with:
          version: ${{ env.UPDATECLI_VERSION }}
      - uses: actions/create-github-app-token@86576b355dd19da0519e0bdb63d8edb5bcf76a25 # v1.7.0
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: "UpdateCLI"
        run: |
          updatecli apply
        env:
          UPDATECLI_GITHUB_USER: ${{ env.UPDATECLI_GITHUB_USER }}
          UPDATECLI_GITHUB_EMAIL: ${{ env.UPDATECLI_GITHUB_EMAIL }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          UPDATECLI_GH_ACTION: true
